# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='est_end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
