# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-24 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20161024_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='end_time',
        ),
    ]
