# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20161111_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='est_end_time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start_time',
            field=models.CharField(max_length=25),
        ),
    ]
