# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_remove_meetup_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
