# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-12-05 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20161111_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_attending',
        ),
    ]
