# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
    ]
