# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-24 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='MeetUp',
        ),
    ]
