# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.CharField(max_length=10),
        ),
    ]
