# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20161111_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
